USE [master]
GO
/****** Object:  Database [shop_db]    Script Date: 31.05.2023 22:02:33 ******/
CREATE DATABASE [shop_db]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'shop_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\shop_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'shop_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\shop_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [shop_db] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [shop_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [shop_db] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [shop_db] SET ANSI_NULLS OFF
GO
ALTER DATABASE [shop_db] SET ANSI_PADDING OFF
GO
ALTER DATABASE [shop_db] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [shop_db] SET ARITHABORT OFF
GO
ALTER DATABASE [shop_db] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [shop_db] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [shop_db] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [shop_db] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [shop_db] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [shop_db] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [shop_db] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [shop_db] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [shop_db] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [shop_db] SET  DISABLE_BROKER
GO
ALTER DATABASE [shop_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [shop_db] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [shop_db] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [shop_db] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [shop_db] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [shop_db] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [shop_db] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [shop_db] SET RECOVERY SIMPLE
GO
ALTER DATABASE [shop_db] SET  MULTI_USER
GO
ALTER DATABASE [shop_db] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [shop_db] SET DB_CHAINING OFF
GO
ALTER DATABASE [shop_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [shop_db] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [shop_db] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [shop_db] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
ALTER DATABASE [shop_db] SET QUERY_STORE = OFF
GO
USE [shop_db]
GO
USE [shop_db]
GO
/****** Object:  Sequence [dbo].[item_seq]    Script Date: 31.05.2023 22:02:33 ******/
CREATE SEQUENCE [dbo].[item_seq]
 AS [bigint]
 START WITH 1
 INCREMENT BY 50
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE
GO
USE [shop_db]
GO
/****** Object:  Sequence [dbo].[order_item_seq]    Script Date: 31.05.2023 22:02:33 ******/
CREATE SEQUENCE [dbo].[order_item_seq]
 AS [bigint]
 START WITH 1
 INCREMENT BY 50
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE
GO
USE [shop_db]
GO
/****** Object:  Sequence [dbo].[orders_seq]    Script Date: 31.05.2023 22:02:33 ******/
CREATE SEQUENCE [dbo].[orders_seq]
 AS [bigint]
 START WITH 1
 INCREMENT BY 50
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE
GO
USE [shop_db]
GO
/****** Object:  Sequence [dbo].[tmp_seq]    Script Date: 31.05.2023 22:02:33 ******/
CREATE SEQUENCE [dbo].[tmp_seq]
 AS [bigint]
 START WITH 1
 INCREMENT BY 50
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE
GO
/****** Object:  Table [dbo].[item]    Script Date: 31.05.2023 22:02:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[item](
	[id] [bigint] NOT NULL,
	[img_url] [varchar](255) NULL,
	[name] [varchar](255) NULL,
	[price] [numeric](38, 2) NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[order_item]    Script Date: 31.05.2023 22:02:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order_item](
	[order_item_id] [bigint] NOT NULL,
	[amount] [int] NOT NULL,
	[item_id] [bigint] NULL,
	[order_id] [bigint] NULL,
PRIMARY KEY CLUSTERED
(
	[order_item_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[orders]    Script Date: 31.05.2023 22:02:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[order_id] [bigint] NOT NULL,
	[address] [varchar](255) NULL,
	[city] [varchar](255) NULL,
	[created] [datetime2](6) NULL,
	[first_name] [varchar](255) NULL,
	[last_name] [varchar](255) NULL,
	[post_code] [varchar](255) NULL,
PRIMARY KEY CLUSTERED
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tmp]    Script Date: 31.05.2023 22:02:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tmp](
	[id] [bigint] NOT NULL,
	[text] [varchar](255) NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[order_item]  WITH CHECK ADD  CONSTRAINT [FKt4dc2r9nbvbujrljv3e23iibt] FOREIGN KEY([order_id])
REFERENCES [dbo].[orders] ([order_id])
GO
ALTER TABLE [dbo].[order_item] CHECK CONSTRAINT [FKt4dc2r9nbvbujrljv3e23iibt]
GO
USE [master]
GO
ALTER DATABASE [shop_db] SET  READ_WRITE
GO
